### PR TITLE
use File.exist? because Ruby 3.2 does not have File.exists?

### PR DESCRIPTION
**Pull request by andy-k**

### CODE REVIEW

**Comment by dentarg** [comment]
I merged this PR over at https://github.com/spinels/racksh and published `spinels-racksh` (https://rubygems.org/gems/spinels-racksh)

**Comment by rorra** [comment]
hi @sickill  , why did the PR didn't get merged? it is a needed update for newer version of ruby and was raised back in 2022... I can help with the gem maintenance if needed

**Comment by sickill** [comment]
Hey guys. Thanks for this. I don't use Ruby anymore and I don't have many opportunities to maintain this gem or review/test PRs. Let me try to publish this to rubygems right now :crossed_fingers:

**Comment by sickill** [comment]
Published: https://rubygems.org/gems/racksh/versions/1.0.1

**Pull request merged**
